name: Android Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for Gradle
      run: chmod +x ./gradlew

    # Если google-services.json отсутствует — игнорируем
    - name: Create dummy google-services.json if missing
      run: |
        if [ ! -f "app/google-services.json" ]; then
          echo '{"project_info": {}}' > app/google-services.json
        fi

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: App1-Sender-Debug
        path: app/build/outputs/apk/debug/*.apk